### ISSUE TITLE
Feedback on week 8 project progress

### ISSUE THREAD

**Issue by damithc** [damithc/foo#6]
* See [mid-v1.2 progress guide](https://nus-cs2103-ay1819s1.github.io/cs2103-website/admin/project-w08-mid-v12.html) for more details of the activities mentioned below.
* Mid-milestone progress reports are FYI only. They are not graded.

### Leftovers from v1.1

- [ ]  Auto-publishing set up for the team repo and the website is available at {url here} (:exclamation: try to do by next milestone)
* README page:
  - [ ]  Some parts not related to your product are removed (:exclamation: try to do by next milestone)
  - [ ]  se-edu/addressbook-level4 acknowledged (:exclamation: try to do by next milestone)
  - [ ]  `Ui.png` has been updated (:exclamation: try to do by next milestone)

### Recommended progress for the upcoming milestone

- [x]  Issue labels set up e.g., `type.*`, `priority.*`, `severity.*` (:heavy_check_mark: well done!)
- [x]  Milestones created e.g., `v1.2`, `v1.3`, `v1.4` (:heavy_check_mark: well done!)
- [x]  User stories converted to issues e.g., [#23]() (:heavy_check_mark: well done!)
- [x]  User stories prioritized using `priority.*` labels e.g., [#23]() (:heavy_check_mark: well done!)
*  Milestone v1.2 planned 
   - [x]  A suitable deadline set (:heavy_check_mark: well done!)
   - [x]  Issues allocated to it e.g., [#23]() (:heavy_check_mark: well done!)
- [x]  Build passing (checked at [this commit]()) (:heavy_check_mark: well done!)

### Leftovers from v1.1

* Used forking workflow:
  - [ ]  Forked team repo (:exclamation: try to do by next milestone)
  - [ ]  Created PRs #15, #34 (:exclamation: try to do by next milestone)
  - [ ]  At least some PRs are using branches  #15 (:exclamation: try to do by next milestone)
  - [ ]  Gave review comments to other PRs example  (:exclamation: try to do by next milestone)
- [ ]  Merged updates to documents (:exclamation: try to do by next milestone)
- [ ]  `abcd.png` uploaded and linked from AboutUs page, merged (:exclamation: try to do by next milestone) 

### Recommended progress for the upcoming milestone

- [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
- [x]  Has issues assigned for the next milestone  (:heavy_check_mark: well done!)

Tutor: @tutorJohn

Note that the above observations were done by a bot and reflects work done upto {deadline} only. Please reply in this thread if there are any inaccuracies in the above observations.
