### ISSUE TITLE
Feedback on week 9 project progress

### ISSUE THREAD

**Issue by damithc** [damithc/foo#7]
* See [v1.2 progress guide](https://nus-cs2103-ay1819s1.github.io/cs2103-website/admin/project-w09-v12.html) for more details of the activities mentioned below.

### Leftovers from v1.1

- [ ]  Auto-publishing set up for the team repo and the website is available at {url here} (:exclamation: try to do by next milestone)
* README page:
  - [ ]  Some parts not related to your product are removed (:exclamation: try to do by next milestone)
  - [ ]  se-edu/addressbook-level4 acknowledged (:exclamation: try to do by next milestone)
  - [ ]  `Ui.png` has been updated (:exclamation: try to do by next milestone)

### Recommended progress for v1.2

- [x]  Issue labels set up e.g., `type.*`, `priority.*` (:heavy_check_mark: well done!)
- [x]  Milestones created e.g., `v1.2`, `v1.3`, `v1.4` (:heavy_check_mark: well done!)
- [x]  Some issues marked as `type.Story` e.g., [#23](put_link_here) (:heavy_check_mark: well done!)
- [x]  Some issues prioritized using `priority.*` labels e.g., [#23]() (:heavy_check_mark: well done!)
*  Milestone v1.2 _managed_ systematically
   - [x]  A suitable deadline set (:heavy_check_mark: well done!)
   - [x]  Issues allocated to it e.g., [#23]() (:heavy_check_mark: well done!)
   - [x]  All issues/PRs in it are closed/merged (:heavy_check_mark: well done!)
   - [x]  Milestone closed (:heavy_check_mark: well done!)
   - [x]  Code tagged as `v1.2` (:heavy_check_mark: well done!)
- [x]  Build passing (checked at [this commit](link_to_commit)) (:heavy_check_mark: well done!)
- [x]  Some issues assigned to milestone v1.3

Not graded:
- [x] User Guide updated for v1.2  (:+1:  Kudos!)

### Leftovers from v1.1

* Used forking workflow:
  - [ ]  Forked team repo (:exclamation: try to do by next milestone)
  - [ ]  Created PRs #15, #34 (:exclamation: try to do by next milestone)
  - [ ]  At least some PRs are using branches  #15 (:exclamation: try to do by next milestone)
  - [ ]  Gave review comments to other PRs example  (:exclamation: try to do by next milestone)
- [ ]  Merged updates to documents (:exclamation: try to do by next milestone)
- [ ]  `abcd.png` uploaded and linked from AboutUs page, merged (:exclamation: try to do by next milestone) 

### Recommended progress for v1.2

- [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
- [x]  Merged updates to the Developer Guide (:heavy_check_mark: well done!)
- [x]  Has issues/PRs assigned for the v1.2 milestone (:heavy_check_mark: well done!)

Tutor: @tutorJohn

Note that the above observations were done by a bot and reflects work done upto {deadline} only. Please reply in this thread if there are any inaccuracies in the above observations.

**Comment by damithc** [comment]
harithadiv/ped-> issue 7:
This issue is not accepted as it was created/updated outside the PE duration (`2020-04-01 11:45:00`-`2020-04-01 14:15:00`)
